language: node_js
node_js: node
cache:
  directories:
    - node_modules
script:
  - npm test
env:
  - CI=true

install:
  - sudo pip install pygments
  - wget https://github.com/gohugoio/hugo/releases/download/v0.48/hugo_0.48_Linux-64bit.deb -O /tmp/hugo.deb && sudo dpkg -i /tmp/hugo.deb
  - rm -rf public || exit 0

script:
  - pygmentize -V
  - hugo -v

before_deploy:
  - npm install netlify-cli -g
  # - npm run build

deploy:
  provider: script
  script: netlify deploy -s $NETLIFY_SITE_ID -a $NETLIFY_ACCESS_TOKEN -d ./public --message "deployment from CI"
  skip_cleanup: true
  on:
    branch: master