baseurl = "/"
disqusShortname = "priyankt68"
googleAnalytics = "UA-93098302-1"
languageCode = "en-US"
theme = "hugo-sustain"
title = "Priyank Trivedi"
enableEmoji = true

[[menu.main]]
identifier = "blog"
name = "blog"
url = "/blog/"
weight = 1

# [[menu.main]]
#   name = "projects"
#   identifier = "projects"
#   weight = 200
#   url = "/projects/"

[params]
author = "Priyank Trivedi"
avatar = "profile.png"
custom_css = []
custom_js = []
description = "Code Folktale"
organisation_address = "https://zenatix.com"
organisation_name = "Zenatix"
[permalinks]
post = "/:year/:month/:day/:slug"
[social]
Email = "priyank.trivedi@zenatix.com"
Github = "priyankt68"
Twitter = "priyankt68"
